#!/usr/bin/sh
if [ "$2" = "" ]
  then
  echo "Warning: second argument is null"
  echo "copy $1 from local to xingshi@hpc-login2.usc.edu:/home/nlg-05/xingshi/hanjing ...."
  scp -i hanjing.rsa $1 xingshi@hpc-login2.usc.edu:/home/nlg-05/xingshi/hanjing
  echo "copy done !!!"
  else
  echo "copy $1 from local to xingshi@hpc-login2.usc.edu:/home/nlg-05/xingshi/hanjing/$2 ...."
  scp -i hanjing.rsa -r $1 xingshi@hpc-login2.usc.edu:/home/nlg-05/xingshi/hanjing/$2 
  echo "copy done !!!"
fi
