# Site settings
title: Chinese Rap
email: xingshi@usc.edu
description: "Generate Topical Poetry"

baseurl: "http://52.24.230.241/rap/"
url: "http://52.24.230.241/rap/"

# Build settings
markdown: kramdown
permalink: pretty
